# Generated by xmbedinit(https://github.com/maskedw/xmbedinit)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions(
        -DMBED_DEBUG
        -DDMBED_TRAP_ERRORS_ENABLED=1
    )
endif()

set(mbed_config_definitions
    # "-DMBED_CONF_LORA_APPLICATION_EUI={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}" # set by library:lora
    # "-DMBED_CONF_LORA_APPLICATION_KEY={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}" # set by library:lora
    # "-DMBED_CONF_LORA_APPSKEY={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}" # set by library:lora
    # "-DMBED_CONF_LORA_DEVICE_EUI={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}" # set by library:lora
    # "-DMBED_CONF_LORA_NWKSKEY={0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}" # set by library:lora
    -DCLOCK_SOURCE=USE_PLL_MSI                              # set by target:NUCLEO_L476RG
    -DMBED_CONF_CELLULAR_RANDOM_MAX_START_DELAY=0           # set by library:cellular
    -DMBED_CONF_CELLULAR_USE_APN_LOOKUP=1                   # set by library:cellular
    -DMBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE=256          # set by library:drivers
    -DMBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE=256          # set by library:drivers
    -DMBED_CONF_EVENTS_PRESENT=1                            # set by library:events
    -DMBED_CONF_EVENTS_SHARED_DISPATCH_FROM_APPLICATION=0   # set by library:events
    -DMBED_CONF_EVENTS_SHARED_EVENTSIZE=256                 # set by library:events
    -DMBED_CONF_EVENTS_SHARED_HIGHPRIO_EVENTSIZE=256        # set by library:events
    -DMBED_CONF_EVENTS_SHARED_HIGHPRIO_STACKSIZE=1024       # set by library:events
    -DMBED_CONF_EVENTS_SHARED_STACKSIZE=1024                # set by library:events
    -DMBED_CONF_EVENTS_USE_LOWPOWER_TIMER_TICKER=0          # set by library:events
    -DMBED_CONF_FILESYSTEM_PRESENT=1                        # set by library:filesystem
    -DMBED_CONF_LORA_ADR_ON=1                               # set by library:lora
    -DMBED_CONF_LORA_APP_PORT=15                            # set by library:lora
    -DMBED_CONF_LORA_DEVICE_ADDRESS=0x00000000              # set by library:lora
    -DMBED_CONF_LORA_DUTY_CYCLE_ON=1                        # set by library:lora
    -DMBED_CONF_LORA_LBT_ON=0                               # set by library:lora
    -DMBED_CONF_LORA_NB_TRIALS=12                           # set by library:lora
    -DMBED_CONF_LORA_OVER_THE_AIR_ACTIVATION=1              # set by library:lora
    -DMBED_CONF_LORA_PHY=0                                  # set by library:lora
    -DMBED_CONF_LORA_PUBLIC_NETWORK=1                       # set by library:lora
    -DMBED_CONF_LORA_TX_MAX_SIZE=64                         # set by library:lora
    -DMBED_CONF_NSAPI_PRESENT=1                             # set by library:nsapi
    -DMBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE=9600      # set by library:platform
    -DMBED_CONF_PLATFORM_FORCE_NON_COPYABLE_ERROR=0         # set by library:platform
    -DMBED_CONF_PLATFORM_STDIO_BAUD_RATE=9600               # set by library:platform
    -DMBED_CONF_PLATFORM_STDIO_BUFFERED_SERIAL=0            # set by library:platform
    -DMBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES=0           # set by library:platform
    -DMBED_CONF_PLATFORM_STDIO_CONVERT_TTY_NEWLINES=0       # set by library:platform
    -DMBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT=1              # set by library:platform
    -DMBED_CONF_PPP_CELL_IFACE_APN_LOOKUP=1                 # set by library:ppp-cell-iface
    -DMBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE=256    # set by library:ppp-cell-iface
    -DMBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT=8000       # set by library:ppp-cell-iface
    -DMBED_CONF_PPP_CELL_IFACE_BAUD_RATE=115200             # set by library:ppp-cell-iface
    -DMBED_CONF_RTOS_PRESENT=1                              # set by library:rtos
    -DMBED_CONF_TARGET_LOWPOWERTIMER_LPTIM=1                # set by target:NUCLEO_L476RG
    -DMBED_CONF_TARGET_LSE_AVAILABLE=1                      # set by target:FAMILY_STM32
    -DMBED_LFS_BLOCK_SIZE=512                               # set by library:littlefs
    -DMBED_LFS_ENABLE_INFO=0                                # set by library:littlefs
    -DMBED_LFS_INTRINSICS=1                                 # set by library:littlefs
    -DMBED_LFS_LOOKAHEAD=512                                # set by library:littlefs
    -DMBED_LFS_PROG_SIZE=64                                 # set by library:littlefs
    -DMBED_LFS_READ_SIZE=64                                 # set by library:littlefs
    -DNVSTORE_ENABLED=1                                     # set by library:nvstore
    -DNVSTORE_MAX_KEYS=16                                   # set by library:nvstore
    -DUNITY_INCLUDE_CONFIG_H                                # defined by library:utest
)

set(mbed_warning_opts
    -Wall
    -Wextra
    -Wno-unused-parameter
    -Wno-missing-field-initializers
)

set(mbed_arch_opts
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
)

set(mbed_extra_opts
    -fmessage-length=0
    -fno-exceptions
    -fno-builtin
    -ffunction-sections
    -fdata-sections
    -funsigned-char
    -fno-delete-null-pointer-checks
    -fomit-frame-pointer
)

set(mbed_asm_flags
    -x
    assembler-with-cpp
    ${mbed_arch_opts}
    ${mbed_warning_opts}
    ${mbed_extra_opts}
)

include_directories(
    mbed-os
    mbed-os/cmsis
    mbed-os/cmsis/TARGET_CORTEX_M
    mbed-os/drivers
    mbed-os/events
    mbed-os/events/equeue
    mbed-os/features
    mbed-os/features/cellular
    mbed-os/features/cellular/easy_cellular
    mbed-os/features/cellular/framework
    mbed-os/features/cellular/framework/API
    mbed-os/features/cellular/framework/AT
    mbed-os/features/cellular/framework/common
    mbed-os/features/cellular/framework/targets
    mbed-os/features/cellular/framework/targets/QUECTEL
    mbed-os/features/cellular/framework/targets/QUECTEL/BC95
    mbed-os/features/cellular/framework/targets/QUECTEL/BG96
    mbed-os/features/cellular/framework/targets/TELIT
    mbed-os/features/cellular/framework/targets/TELIT/HE910
    mbed-os/features/cellular/framework/targets/UBLOX
    mbed-os/features/cellular/framework/targets/UBLOX/LISA_U
    mbed-os/features/filesystem
    mbed-os/features/filesystem/bd
    mbed-os/features/filesystem/fat
    mbed-os/features/filesystem/fat/ChaN
    mbed-os/features/filesystem/littlefs
    mbed-os/features/filesystem/littlefs/littlefs
    mbed-os/features/lorawan
    mbed-os/features/lorawan/lorastack
    mbed-os/features/lorawan/lorastack/mac
    mbed-os/features/lorawan/lorastack/phy
    mbed-os/features/lorawan/system
    mbed-os/features/mbedtls
    mbed-os/features/mbedtls/importer
    mbed-os/features/mbedtls/inc
    mbed-os/features/mbedtls/inc/mbedtls
    mbed-os/features/mbedtls/platform
    mbed-os/features/mbedtls/platform/inc
    mbed-os/features/mbedtls/platform/src
    mbed-os/features/mbedtls/src
    mbed-os/features/mbedtls/targets
    mbed-os/features/mbedtls/targets/TARGET_STM
    mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32L4
    mbed-os/features/nanostack
    mbed-os/features/netsocket
    mbed-os/features/netsocket/cellular
    mbed-os/features/netsocket/cellular/generic_modem_driver
    mbed-os/features/nvstore
    mbed-os/features/nvstore/source
    mbed-os/features/storage
    mbed-os/hal
    mbed-os/hal/storage_abstraction
    mbed-os/platform
    mbed-os/rtos
    mbed-os/rtos/TARGET_CORTEX
    mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M
    mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC
    mbed-os/rtos/TARGET_CORTEX/rtx4
    mbed-os/rtos/TARGET_CORTEX/rtx5
    mbed-os/rtos/TARGET_CORTEX/rtx5/Include
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7
    mbed-os/rtos/TARGET_CORTEX/rtx5/Source
    mbed-os/targets
    mbed-os/targets/TARGET_STM
    mbed-os/targets/TARGET_STM/TARGET_STM32L4
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device
)

set(mbed_link_libraries
    stdc++
    supc++
    m
    c
    gcc
    nosys
)

set(mbed_linker_flags
    -Wl,--gc-sections
    -Wl,--wrap,main
    -Wl,--wrap,_malloc_r
    -Wl,--wrap,_free_r
    -Wl,--wrap,_realloc_r
    -Wl,--wrap,_memalign_r
    -Wl,--wrap,_calloc_r
    -Wl,--wrap,exit
    -Wl,--wrap,atexit
    -Wl,-n
)

add_definitions(
    ${mbed_config_definitions}
    -DARM_MATH_CM4
    -DDEVICE_ANALOGIN=1
    -DDEVICE_ANALOGOUT=1
    -DDEVICE_CAN=1
    -DDEVICE_FLASH=1
    -DDEVICE_I2C=1
    -DDEVICE_I2CSLAVE=1
    -DDEVICE_I2C_ASYNCH=1
    -DDEVICE_INTERRUPTIN=1
    -DDEVICE_LOWPOWERTIMER=1
    -DDEVICE_PORTIN=1
    -DDEVICE_PORTINOUT=1
    -DDEVICE_PORTOUT=1
    -DDEVICE_PWMOUT=1
    -DDEVICE_RTC=1
    -DDEVICE_SERIAL=1
    -DDEVICE_SERIAL_ASYNCH=1
    -DDEVICE_SERIAL_FC=1
    -DDEVICE_SLEEP=1
    -DDEVICE_SPI=1
    -DDEVICE_SPISLAVE=1
    -DDEVICE_SPI_ASYNCH=1
    -DDEVICE_STDIO_MESSAGES=1
    -DDEVICE_TRNG=1
    -DMBED_BUILD_TIMESTAMP=1527151532.63
    -DTARGET_CORTEX
    -DTARGET_CORTEX_M
    -DTARGET_DEBUG
    -DTARGET_FAMILY_STM32
    -DTARGET_FF_ARDUINO
    -DTARGET_FF_MORPHO
    -DTARGET_LIKE_CORTEX_M4
    -DTARGET_LIKE_MBED
    -DTARGET_M4
    -DTARGET_NUCLEO_L476RG
    -DTARGET_RTOS_M4_M7
    -DTARGET_STM
    -DTARGET_STM32L4
    -DTARGET_STM32L476RG
    -DTARGET_STM32L476xG
    -DTARGET_UVISOR_UNSUPPORTED
    -DTOOLCHAIN_GCC
    -DTOOLCHAIN_GCC_ARM
    -DTOOLCHAIN_object
    -DTRANSACTION_QUEUE_SIZE_SPI=2
    -DTWO_RAM_REGIONS
    -DUSBHOST_OTHER
    -D__CMSIS_RTOS
    -D__CORTEX_M4
    -D__FPU_PRESENT=1
    -D__MBED_CMSIS_RTOS_CM
    -D__MBED__=1
)

set(mbed_sources
    mbed-os/drivers/AnalogIn.cpp
    mbed-os/drivers/BusIn.cpp
    mbed-os/drivers/BusInOut.cpp
    mbed-os/drivers/BusOut.cpp
    mbed-os/drivers/CAN.cpp
    mbed-os/drivers/Ethernet.cpp
    mbed-os/drivers/FlashIAP.cpp
    mbed-os/drivers/I2C.cpp
    mbed-os/drivers/I2CSlave.cpp
    mbed-os/drivers/InterruptIn.cpp
    mbed-os/drivers/InterruptManager.cpp
    mbed-os/drivers/MbedCRC.cpp
    mbed-os/drivers/RawSerial.cpp
    mbed-os/drivers/SPI.cpp
    mbed-os/drivers/SPISlave.cpp
    mbed-os/drivers/Serial.cpp
    mbed-os/drivers/SerialBase.cpp
    mbed-os/drivers/TableCRC.cpp
    mbed-os/drivers/Ticker.cpp
    mbed-os/drivers/Timeout.cpp
    mbed-os/drivers/Timer.cpp
    mbed-os/drivers/TimerEvent.cpp
    mbed-os/drivers/UARTSerial.cpp
    mbed-os/events/EventQueue.cpp
    mbed-os/events/equeue/equeue.c
    mbed-os/events/equeue/equeue_mbed.cpp
    mbed-os/events/equeue/equeue_posix.c
    mbed-os/events/mbed_shared_queues.cpp
    # mbed-os/features/cellular/easy_cellular/CellularConnectionFSM.cpp
    # mbed-os/features/cellular/easy_cellular/EasyCellularConnection.cpp
    # mbed-os/features/cellular/framework/AT/ATHandler.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularBase.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularDevice.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularInformation.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularNetwork.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularPower.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularSIM.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularSMS.cpp
    # mbed-os/features/cellular/framework/AT/AT_CellularStack.cpp
    # mbed-os/features/cellular/framework/common/CellularUtil.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularNetwork.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.cpp
    # mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
    # mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
    # mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularNetwork.cpp
    # mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularPower.cpp
    # mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U.cpp
    # mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularNetwork.cpp
    # mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularPower.cpp
    mbed-os/features/filesystem/Dir.cpp
    mbed-os/features/filesystem/File.cpp
    mbed-os/features/filesystem/FileSystem.cpp
    mbed-os/features/filesystem/bd/ChainingBlockDevice.cpp
    mbed-os/features/filesystem/bd/ExhaustibleBlockDevice.cpp
    mbed-os/features/filesystem/bd/HeapBlockDevice.cpp
    mbed-os/features/filesystem/bd/MBRBlockDevice.cpp
    mbed-os/features/filesystem/bd/ObservingBlockDevice.cpp
    mbed-os/features/filesystem/bd/ProfilingBlockDevice.cpp
    mbed-os/features/filesystem/bd/ReadOnlyBlockDevice.cpp
    mbed-os/features/filesystem/bd/SlicingBlockDevice.cpp
    # mbed-os/features/filesystem/fat/ChaN/ff.cpp
    # mbed-os/features/filesystem/fat/ChaN/ffunicode.cpp
    # mbed-os/features/filesystem/fat/FATFileSystem.cpp
    mbed-os/features/filesystem/littlefs/LittleFileSystem.cpp
    mbed-os/features/filesystem/littlefs/littlefs/lfs.c
    mbed-os/features/filesystem/littlefs/littlefs/lfs_util.c
    # mbed-os/features/lorawan/LoRaWANInterface.cpp
    # mbed-os/features/lorawan/LoRaWANStack.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMac.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMacCommand.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMacMcps.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMacMib.cpp
    # mbed-os/features/lorawan/lorastack/mac/LoRaMacMlme.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHY.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYCN779.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYEU433.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYEU868.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
    # mbed-os/features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
    # mbed-os/features/lorawan/system/LoRaWANTimer.cpp
    # mbed-os/features/mbedtls/platform/src/mbed_trng.c
    # mbed-os/features/mbedtls/src/aes.c
    # mbed-os/features/mbedtls/src/aesni.c
    # mbed-os/features/mbedtls/src/arc4.c
    # mbed-os/features/mbedtls/src/asn1parse.c
    # mbed-os/features/mbedtls/src/asn1write.c
    # mbed-os/features/mbedtls/src/base64.c
    # mbed-os/features/mbedtls/src/bignum.c
    # mbed-os/features/mbedtls/src/blowfish.c
    # mbed-os/features/mbedtls/src/camellia.c
    # mbed-os/features/mbedtls/src/ccm.c
    # mbed-os/features/mbedtls/src/certs.c
    # mbed-os/features/mbedtls/src/cipher.c
    # mbed-os/features/mbedtls/src/cipher_wrap.c
    # mbed-os/features/mbedtls/src/cmac.c
    # mbed-os/features/mbedtls/src/ctr_drbg.c
    # mbed-os/features/mbedtls/src/debug.c
    # mbed-os/features/mbedtls/src/des.c
    # mbed-os/features/mbedtls/src/dhm.c
    # mbed-os/features/mbedtls/src/ecdh.c
    # mbed-os/features/mbedtls/src/ecdsa.c
    # mbed-os/features/mbedtls/src/ecjpake.c
    # mbed-os/features/mbedtls/src/ecp.c
    # mbed-os/features/mbedtls/src/ecp_curves.c
    # mbed-os/features/mbedtls/src/entropy.c
    # mbed-os/features/mbedtls/src/entropy_poll.c
    # mbed-os/features/mbedtls/src/error.c
    # mbed-os/features/mbedtls/src/gcm.c
    # mbed-os/features/mbedtls/src/havege.c
    # mbed-os/features/mbedtls/src/hmac_drbg.c
    # mbed-os/features/mbedtls/src/md.c
    # mbed-os/features/mbedtls/src/md2.c
    # mbed-os/features/mbedtls/src/md4.c
    # mbed-os/features/mbedtls/src/md5.c
    # mbed-os/features/mbedtls/src/md_wrap.c
    # mbed-os/features/mbedtls/src/memory_buffer_alloc.c
    # mbed-os/features/mbedtls/src/net_sockets.c
    # mbed-os/features/mbedtls/src/oid.c
    # mbed-os/features/mbedtls/src/padlock.c
    # mbed-os/features/mbedtls/src/pem.c
    # mbed-os/features/mbedtls/src/pk.c
    # mbed-os/features/mbedtls/src/pk_wrap.c
    # mbed-os/features/mbedtls/src/pkcs11.c
    # mbed-os/features/mbedtls/src/pkcs12.c
    # mbed-os/features/mbedtls/src/pkcs5.c
    # mbed-os/features/mbedtls/src/pkparse.c
    # mbed-os/features/mbedtls/src/pkwrite.c
    # mbed-os/features/mbedtls/src/platform.c
    # mbed-os/features/mbedtls/src/ripemd160.c
    # mbed-os/features/mbedtls/src/rsa.c
    # mbed-os/features/mbedtls/src/rsa_internal.c
    # mbed-os/features/mbedtls/src/sha1.c
    # mbed-os/features/mbedtls/src/sha256.c
    # mbed-os/features/mbedtls/src/sha512.c
    # mbed-os/features/mbedtls/src/ssl_cache.c
    # mbed-os/features/mbedtls/src/ssl_ciphersuites.c
    # mbed-os/features/mbedtls/src/ssl_cli.c
    # mbed-os/features/mbedtls/src/ssl_cookie.c
    # mbed-os/features/mbedtls/src/ssl_srv.c
    # mbed-os/features/mbedtls/src/ssl_ticket.c
    # mbed-os/features/mbedtls/src/ssl_tls.c
    # mbed-os/features/mbedtls/src/threading.c
    # mbed-os/features/mbedtls/src/timing.c
    # mbed-os/features/mbedtls/src/version.c
    # mbed-os/features/mbedtls/src/version_features.c
    # mbed-os/features/mbedtls/src/x509.c
    # mbed-os/features/mbedtls/src/x509_create.c
    # mbed-os/features/mbedtls/src/x509_crl.c
    # mbed-os/features/mbedtls/src/x509_crt.c
    # mbed-os/features/mbedtls/src/x509_csr.c
    # mbed-os/features/mbedtls/src/x509write_crt.c
    # mbed-os/features/mbedtls/src/x509write_csr.c
    # mbed-os/features/mbedtls/src/xtea.c
    # mbed-os/features/mbedtls/targets/TARGET_STM/aes_alt.c
    # mbed-os/features/mbedtls/targets/TARGET_STM/md5_alt.c
    # mbed-os/features/mbedtls/targets/TARGET_STM/sha1_alt.c
    # mbed-os/features/mbedtls/targets/TARGET_STM/sha256_alt.c
    # mbed-os/features/mbedtls/targets/hash_wrappers.c
    mbed-os/features/netsocket/NetworkInterface.cpp
    mbed-os/features/netsocket/NetworkStack.cpp
    mbed-os/features/netsocket/Socket.cpp
    mbed-os/features/netsocket/SocketAddress.cpp
    mbed-os/features/netsocket/TCPServer.cpp
    mbed-os/features/netsocket/TCPSocket.cpp
    mbed-os/features/netsocket/UDPSocket.cpp
    mbed-os/features/netsocket/WiFiAccessPoint.cpp
    # mbed-os/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.cpp
    # mbed-os/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
    # mbed-os/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.cpp
    mbed-os/features/netsocket/nsapi_dns.cpp
    mbed-os/features/nvstore/source/nvstore.cpp
    mbed-os/hal/mbed_critical_section_api.c
    mbed-os/hal/mbed_flash_api.c
    mbed-os/hal/mbed_gpio.c
    mbed-os/hal/mbed_itm_api.c
    mbed-os/hal/mbed_lp_ticker_api.c
    mbed-os/hal/mbed_pinmap_common.c
    mbed-os/hal/mbed_sleep_manager.c
    mbed-os/hal/mbed_ticker_api.c
    mbed-os/hal/mbed_us_ticker_api.c
    mbed-os/platform/ATCmdParser.cpp
    mbed-os/platform/CallChain.cpp
    mbed-os/platform/FileBase.cpp
    mbed-os/platform/FileHandle.cpp
    mbed-os/platform/FilePath.cpp
    mbed-os/platform/FileSystemHandle.cpp
    mbed-os/platform/LocalFileSystem.cpp
    mbed-os/platform/Stream.cpp
    mbed-os/platform/mbed_alloc_wrappers.cpp
    mbed-os/platform/mbed_application.c
    mbed-os/platform/mbed_assert.c
    mbed-os/platform/mbed_board.c
    mbed-os/platform/mbed_critical.c
    mbed-os/platform/mbed_error.c
    mbed-os/platform/mbed_interface.c
    mbed-os/platform/mbed_mem_trace.cpp
    mbed-os/platform/mbed_mktime.c
    mbed-os/platform/mbed_poll.cpp
    mbed-os/platform/mbed_retarget.cpp
    mbed-os/platform/mbed_rtc_time.cpp
    mbed-os/platform/mbed_sdk_boot.c
    mbed-os/platform/mbed_semihost_api.c
    mbed-os/platform/mbed_stats.c
    mbed-os/platform/mbed_wait_api_no_rtos.c
    mbed-os/platform/mbed_wait_api_rtos.cpp
    mbed-os/rtos/ConditionVariable.cpp
    mbed-os/rtos/EventFlags.cpp
    mbed-os/rtos/Kernel.cpp
    mbed-os/rtos/Mutex.cpp
    mbed-os/rtos/RtosTimer.cpp
    mbed-os/rtos/Semaphore.cpp
    mbed-os/rtos/TARGET_CORTEX/SysTimer.cpp
    mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
    mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
    mbed-os/rtos/TARGET_CORTEX/mbed_boot.c
    mbed-os/rtos/TARGET_CORTEX/mbed_rtx_handlers.c
    mbed-os/rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
    mbed-os/rtos/TARGET_CORTEX/rtx4/cmsis_os1.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.S
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_delay.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evflags.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_evr.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_kernel.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_memory.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mempool.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_msgqueue.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_mutex.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_semaphore.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_system.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_timer.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_systick.c
    mbed-os/rtos/TARGET_CORTEX/rtx5/Source/os_tick_ptim.c
    mbed-os/rtos/Thread.cpp
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/PeripheralPins.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/system_clock.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/startup_stm32l476xx.S
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can_legacy.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_comp.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cortex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_crc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_crc_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cryp.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cryp_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dac.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dac_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dcmi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dfsdm.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dfsdm_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma2d.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dsi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_firewall.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash_ramfunc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gfxmmu.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gpio.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hcd.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_i2c.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_i2c_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_irda.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_iwdg.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_lcd.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_lptim.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ltdc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ltdc_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_nand.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_nor.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_opamp.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_opamp_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ospi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pwr.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pwr_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_qspi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rng.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sai.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sai_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sd.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sd_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smartcard.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smartcard_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smbus.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sram.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_swpmi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tsc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_usart.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_usart_ex.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_wwdg.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_adc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_comp.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_crc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_crs.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dac.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dma.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dma2d.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_exti.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_fmc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_gpio.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_i2c.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_lptim.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_lpuart.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_opamp.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_pwr.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rcc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rng.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rtc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_sdmmc.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_spi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_swpmi.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_tim.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usart.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usb.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_utils.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/system_stm32l4xx.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/flash_api.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/gpio_irq_device.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/l4_retarget.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/pwmout_device.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/serial_device.c
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/spi_api.c
    mbed-os/targets/TARGET_STM/analogin_api.c
    mbed-os/targets/TARGET_STM/analogout_api.c
    mbed-os/targets/TARGET_STM/can_api.c
    mbed-os/targets/TARGET_STM/gpio_api.c
    mbed-os/targets/TARGET_STM/gpio_irq_api.c
    mbed-os/targets/TARGET_STM/hal_tick_16b.c
    mbed-os/targets/TARGET_STM/hal_tick_32b.c
    mbed-os/targets/TARGET_STM/i2c_api.c
    mbed-os/targets/TARGET_STM/lp_ticker.c
    mbed-os/targets/TARGET_STM/mbed_overrides.c
    mbed-os/targets/TARGET_STM/pinmap.c
    mbed-os/targets/TARGET_STM/port_api.c
    mbed-os/targets/TARGET_STM/pwmout_api.c
    mbed-os/targets/TARGET_STM/rtc_api.c
    mbed-os/targets/TARGET_STM/serial_api.c
    mbed-os/targets/TARGET_STM/sleep.c
    mbed-os/targets/TARGET_STM/stm_spi_api.c
    mbed-os/targets/TARGET_STM/trng_api.c
    mbed-os/targets/TARGET_STM/us_ticker_16b.c
    mbed-os/targets/TARGET_STM/us_ticker_32b.c
)

set(mbed_headers
    mbed-os/mbed.h
    mbed-os/cmsis/TARGET_CORTEX_M/arm_math.h
    mbed-os/cmsis/TARGET_CORTEX_M/cmsis_armcc.h
    mbed-os/cmsis/TARGET_CORTEX_M/cmsis_armclang.h
    mbed-os/cmsis/TARGET_CORTEX_M/cmsis_compiler.h
    mbed-os/cmsis/TARGET_CORTEX_M/cmsis_gcc.h
    mbed-os/cmsis/TARGET_CORTEX_M/cmsis_iccarm.h
    mbed-os/cmsis/TARGET_CORTEX_M/cmsis_version.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_armv8mbl.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_armv8mml.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm0.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm0plus.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm23.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm3.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm33.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm4.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cm7.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_cmSecureAccess.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_sc000.h
    mbed-os/cmsis/TARGET_CORTEX_M/core_sc300.h
    mbed-os/cmsis/TARGET_CORTEX_M/mpu_armv7.h
    mbed-os/cmsis/TARGET_CORTEX_M/mpu_armv8.h
    mbed-os/cmsis/TARGET_CORTEX_M/tz_context.h
    mbed-os/drivers/AnalogIn.h
    mbed-os/drivers/AnalogOut.h
    mbed-os/drivers/BusIn.h
    mbed-os/drivers/BusInOut.h
    mbed-os/drivers/BusOut.h
    mbed-os/drivers/CAN.h
    mbed-os/drivers/DigitalIn.h
    mbed-os/drivers/DigitalInOut.h
    mbed-os/drivers/DigitalOut.h
    mbed-os/drivers/Ethernet.h
    mbed-os/drivers/FlashIAP.h
    mbed-os/drivers/I2C.h
    mbed-os/drivers/I2CSlave.h
    mbed-os/drivers/InterruptIn.h
    mbed-os/drivers/InterruptManager.h
    mbed-os/drivers/LowPowerTicker.h
    mbed-os/drivers/LowPowerTimeout.h
    mbed-os/drivers/LowPowerTimer.h
    mbed-os/drivers/MbedCRC.h
    mbed-os/drivers/PortIn.h
    mbed-os/drivers/PortInOut.h
    mbed-os/drivers/PortOut.h
    mbed-os/drivers/PwmOut.h
    mbed-os/drivers/RawSerial.h
    mbed-os/drivers/Serial.h
    mbed-os/drivers/SerialBase.h
    mbed-os/drivers/SerialWireOutput.h
    mbed-os/drivers/SPI.h
    mbed-os/drivers/SPISlave.h
    mbed-os/drivers/TableCRC.h
    mbed-os/drivers/Ticker.h
    mbed-os/drivers/Timeout.h
    mbed-os/drivers/Timer.h
    mbed-os/drivers/TimerEvent.h
    mbed-os/drivers/UARTSerial.h
    mbed-os/events/Event.h
    mbed-os/events/EventQueue.h
    mbed-os/events/mbed_events.h
    mbed-os/events/mbed_shared_queues.h
    mbed-os/events/equeue/equeue.h
    mbed-os/events/equeue/equeue_platform.h
    mbed-os/features/cellular/easy_cellular/APN_db.h
    mbed-os/features/cellular/easy_cellular/CellularConnectionFSM.h
    mbed-os/features/cellular/easy_cellular/EasyCellularConnection.h
    mbed-os/features/cellular/framework/API/CellularDevice.h
    mbed-os/features/cellular/framework/API/CellularInformation.h
    mbed-os/features/cellular/framework/API/CellularNetwork.h
    mbed-os/features/cellular/framework/API/CellularPower.h
    mbed-os/features/cellular/framework/API/CellularSIM.h
    mbed-os/features/cellular/framework/API/CellularSMS.h
    mbed-os/features/cellular/framework/AT/ATHandler.h
    mbed-os/features/cellular/framework/AT/AT_CellularBase.h
    mbed-os/features/cellular/framework/AT/AT_CellularDevice.h
    mbed-os/features/cellular/framework/AT/AT_CellularInformation.h
    mbed-os/features/cellular/framework/AT/AT_CellularNetwork.h
    mbed-os/features/cellular/framework/AT/AT_CellularPower.h
    mbed-os/features/cellular/framework/AT/AT_CellularSIM.h
    mbed-os/features/cellular/framework/AT/AT_CellularSMS.h
    mbed-os/features/cellular/framework/AT/AT_CellularStack.h
    mbed-os/features/cellular/framework/common/CellularList.h
    mbed-os/features/cellular/framework/common/CellularLog.h
    mbed-os/features/cellular/framework/common/CellularTargets.h
    mbed-os/features/cellular/framework/common/CellularUtil.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularNetwork.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.h
    mbed-os/features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
    mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.h
    mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularNetwork.h
    mbed-os/features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularPower.h
    mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U.h
    mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularNetwork.h
    mbed-os/features/cellular/framework/targets/UBLOX/LISA_U/UBLOX_LISA_U_CellularPower.h
    mbed-os/features/filesystem/Dir.h
    mbed-os/features/filesystem/File.h
    mbed-os/features/filesystem/FileSystem.h
    mbed-os/features/filesystem/mbed_filesystem.h
    mbed-os/features/filesystem/bd/BlockDevice.h
    mbed-os/features/filesystem/bd/ChainingBlockDevice.h
    mbed-os/features/filesystem/bd/ExhaustibleBlockDevice.h
    mbed-os/features/filesystem/bd/HeapBlockDevice.h
    mbed-os/features/filesystem/bd/MBRBlockDevice.h
    mbed-os/features/filesystem/bd/ObservingBlockDevice.h
    mbed-os/features/filesystem/bd/ProfilingBlockDevice.h
    mbed-os/features/filesystem/bd/ReadOnlyBlockDevice.h
    mbed-os/features/filesystem/bd/SlicingBlockDevice.h
    mbed-os/features/filesystem/fat/FATFileSystem.h
    mbed-os/features/filesystem/fat/ChaN/diskio.h
    mbed-os/features/filesystem/fat/ChaN/ff.h
    mbed-os/features/filesystem/fat/ChaN/ffconf.h
    mbed-os/features/filesystem/fat/ChaN/integer.h
    mbed-os/features/filesystem/littlefs/LittleFileSystem.h
    mbed-os/features/filesystem/littlefs/littlefs/lfs.h
    mbed-os/features/filesystem/littlefs/littlefs/lfs_util.h
    mbed-os/features/lorawan/LoRaRadio.h
    mbed-os/features/lorawan/LoRaWANBase.h
    mbed-os/features/lorawan/LoRaWANInterface.h
    mbed-os/features/lorawan/LoRaWANStack.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMac.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMacChannelPlan.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMacCommand.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMacCrypto.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMacMcps.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMacMib.h
    mbed-os/features/lorawan/lorastack/mac/LoRaMacMlme.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHY.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYAS923.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYAU915.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYCN470.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYCN779.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYEU433.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYEU868.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYIN865.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYKR920.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYUS915.h
    mbed-os/features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
    mbed-os/features/lorawan/lorastack/phy/lora_phy_ds.h
    mbed-os/features/lorawan/system/LoRaWANTimer.h
    mbed-os/features/lorawan/system/lorawan_data_structures.h
    mbed-os/features/mbedtls/inc/mbedtls/aes.h
    mbed-os/features/mbedtls/inc/mbedtls/aesni.h
    mbed-os/features/mbedtls/inc/mbedtls/arc4.h
    mbed-os/features/mbedtls/inc/mbedtls/asn1.h
    mbed-os/features/mbedtls/inc/mbedtls/asn1write.h
    mbed-os/features/mbedtls/inc/mbedtls/base64.h
    mbed-os/features/mbedtls/inc/mbedtls/bignum.h
    mbed-os/features/mbedtls/inc/mbedtls/blowfish.h
    mbed-os/features/mbedtls/inc/mbedtls/bn_mul.h
    mbed-os/features/mbedtls/inc/mbedtls/camellia.h
    mbed-os/features/mbedtls/inc/mbedtls/ccm.h
    mbed-os/features/mbedtls/inc/mbedtls/certs.h
    mbed-os/features/mbedtls/inc/mbedtls/check_config.h
    mbed-os/features/mbedtls/inc/mbedtls/cipher.h
    mbed-os/features/mbedtls/inc/mbedtls/cipher_internal.h
    mbed-os/features/mbedtls/inc/mbedtls/cmac.h
    mbed-os/features/mbedtls/inc/mbedtls/compat-1.3.h
    mbed-os/features/mbedtls/inc/mbedtls/config-no-entropy.h
    mbed-os/features/mbedtls/inc/mbedtls/config.h
    mbed-os/features/mbedtls/inc/mbedtls/ctr_drbg.h
    mbed-os/features/mbedtls/inc/mbedtls/debug.h
    mbed-os/features/mbedtls/inc/mbedtls/des.h
    mbed-os/features/mbedtls/inc/mbedtls/dhm.h
    mbed-os/features/mbedtls/inc/mbedtls/ecdh.h
    mbed-os/features/mbedtls/inc/mbedtls/ecdsa.h
    mbed-os/features/mbedtls/inc/mbedtls/ecjpake.h
    mbed-os/features/mbedtls/inc/mbedtls/ecp.h
    mbed-os/features/mbedtls/inc/mbedtls/ecp_internal.h
    mbed-os/features/mbedtls/inc/mbedtls/entropy.h
    mbed-os/features/mbedtls/inc/mbedtls/entropy_poll.h
    mbed-os/features/mbedtls/inc/mbedtls/error.h
    mbed-os/features/mbedtls/inc/mbedtls/gcm.h
    mbed-os/features/mbedtls/inc/mbedtls/havege.h
    mbed-os/features/mbedtls/inc/mbedtls/hmac_drbg.h
    mbed-os/features/mbedtls/inc/mbedtls/md.h
    mbed-os/features/mbedtls/inc/mbedtls/md2.h
    mbed-os/features/mbedtls/inc/mbedtls/md4.h
    mbed-os/features/mbedtls/inc/mbedtls/md5.h
    mbed-os/features/mbedtls/inc/mbedtls/md_internal.h
    mbed-os/features/mbedtls/inc/mbedtls/memory_buffer_alloc.h
    mbed-os/features/mbedtls/inc/mbedtls/net.h
    mbed-os/features/mbedtls/inc/mbedtls/net_sockets.h
    mbed-os/features/mbedtls/inc/mbedtls/oid.h
    mbed-os/features/mbedtls/inc/mbedtls/padlock.h
    mbed-os/features/mbedtls/inc/mbedtls/pem.h
    mbed-os/features/mbedtls/inc/mbedtls/pk.h
    mbed-os/features/mbedtls/inc/mbedtls/pkcs11.h
    mbed-os/features/mbedtls/inc/mbedtls/pkcs12.h
    mbed-os/features/mbedtls/inc/mbedtls/pkcs5.h
    mbed-os/features/mbedtls/inc/mbedtls/pk_internal.h
    mbed-os/features/mbedtls/inc/mbedtls/platform.h
    mbed-os/features/mbedtls/inc/mbedtls/platform_time.h
    mbed-os/features/mbedtls/inc/mbedtls/ripemd160.h
    mbed-os/features/mbedtls/inc/mbedtls/rsa.h
    mbed-os/features/mbedtls/inc/mbedtls/rsa_internal.h
    mbed-os/features/mbedtls/inc/mbedtls/sha1.h
    mbed-os/features/mbedtls/inc/mbedtls/sha256.h
    mbed-os/features/mbedtls/inc/mbedtls/sha512.h
    mbed-os/features/mbedtls/inc/mbedtls/ssl.h
    mbed-os/features/mbedtls/inc/mbedtls/ssl_cache.h
    mbed-os/features/mbedtls/inc/mbedtls/ssl_ciphersuites.h
    mbed-os/features/mbedtls/inc/mbedtls/ssl_cookie.h
    mbed-os/features/mbedtls/inc/mbedtls/ssl_internal.h
    mbed-os/features/mbedtls/inc/mbedtls/ssl_ticket.h
    mbed-os/features/mbedtls/inc/mbedtls/threading.h
    mbed-os/features/mbedtls/inc/mbedtls/timing.h
    mbed-os/features/mbedtls/inc/mbedtls/version.h
    mbed-os/features/mbedtls/inc/mbedtls/x509.h
    mbed-os/features/mbedtls/inc/mbedtls/x509_crl.h
    mbed-os/features/mbedtls/inc/mbedtls/x509_crt.h
    mbed-os/features/mbedtls/inc/mbedtls/x509_csr.h
    mbed-os/features/mbedtls/inc/mbedtls/xtea.h
    mbed-os/features/mbedtls/platform/inc/platform_mbed.h
    mbed-os/features/mbedtls/targets/TARGET_STM/aes_alt.h
    mbed-os/features/mbedtls/targets/TARGET_STM/md5_alt.h
    mbed-os/features/mbedtls/targets/TARGET_STM/sha1_alt.h
    mbed-os/features/mbedtls/targets/TARGET_STM/sha256_alt.h
    mbed-os/features/netsocket/CellularBase.h
    mbed-os/features/netsocket/CellularInterface.h
    mbed-os/features/netsocket/emac_stack_mem.h
    mbed-os/features/netsocket/EthInterface.h
    mbed-os/features/netsocket/MeshInterface.h
    mbed-os/features/netsocket/NetworkInterface.h
    mbed-os/features/netsocket/NetworkStack.h
    mbed-os/features/netsocket/nsapi.h
    mbed-os/features/netsocket/nsapi_dns.h
    mbed-os/features/netsocket/nsapi_ppp.h
    mbed-os/features/netsocket/nsapi_types.h
    mbed-os/features/netsocket/Socket.h
    mbed-os/features/netsocket/SocketAddress.h
    mbed-os/features/netsocket/TCPServer.h
    mbed-os/features/netsocket/TCPSocket.h
    mbed-os/features/netsocket/UDPSocket.h
    mbed-os/features/netsocket/WiFiAccessPoint.h
    mbed-os/features/netsocket/WiFiInterface.h
    mbed-os/features/netsocket/cellular/onboard_modem_api.h
    mbed-os/features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.h
    mbed-os/features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.h
    mbed-os/features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.h
    mbed-os/features/nvstore/source/nvstore.h
    mbed-os/hal/analogin_api.h
    mbed-os/hal/analogout_api.h
    mbed-os/hal/buffer.h
    mbed-os/hal/can_api.h
    mbed-os/hal/can_helper.h
    mbed-os/hal/critical_section_api.h
    mbed-os/hal/dma_api.h
    mbed-os/hal/emac_api.h
    mbed-os/hal/ethernet_api.h
    mbed-os/hal/flash_api.h
    mbed-os/hal/gpio_api.h
    mbed-os/hal/gpio_irq_api.h
    mbed-os/hal/i2c_api.h
    mbed-os/hal/itm_api.h
    mbed-os/hal/lp_ticker_api.h
    mbed-os/hal/pinmap.h
    mbed-os/hal/port_api.h
    mbed-os/hal/pwmout_api.h
    mbed-os/hal/rtc_api.h
    mbed-os/hal/serial_api.h
    mbed-os/hal/sleep_api.h
    mbed-os/hal/spi_api.h
    mbed-os/hal/ticker_api.h
    mbed-os/hal/trng_api.h
    mbed-os/hal/us_ticker_api.h
    mbed-os/hal/storage_abstraction/Driver_Common.h
    mbed-os/hal/storage_abstraction/Driver_Storage.h
    mbed-os/platform/ATCmdParser.h
    mbed-os/platform/Callback.h
    mbed-os/platform/CallChain.h
    mbed-os/platform/CircularBuffer.h
    mbed-os/platform/critical.h
    mbed-os/platform/CriticalSectionLock.h
    mbed-os/platform/CThunk.h
    mbed-os/platform/DeepSleepLock.h
    mbed-os/platform/DirHandle.h
    mbed-os/platform/FileBase.h
    mbed-os/platform/FileHandle.h
    mbed-os/platform/FileLike.h
    mbed-os/platform/FilePath.h
    mbed-os/platform/FileSystemHandle.h
    mbed-os/platform/FileSystemLike.h
    mbed-os/platform/FunctionPointer.h
    mbed-os/platform/LocalFileSystem.h
    mbed-os/platform/mbed_application.h
    mbed-os/platform/mbed_assert.h
    mbed-os/platform/mbed_critical.h
    mbed-os/platform/mbed_debug.h
    mbed-os/platform/mbed_error.h
    mbed-os/platform/mbed_interface.h
    mbed-os/platform/mbed_mem_trace.h
    mbed-os/platform/mbed_mktime.h
    mbed-os/platform/mbed_poll.h
    mbed-os/platform/mbed_power_mgmt.h
    mbed-os/platform/mbed_preprocessor.h
    mbed-os/platform/mbed_retarget.h
    mbed-os/platform/mbed_rtc_time.h
    mbed-os/platform/mbed_semihost_api.h
    mbed-os/platform/mbed_sleep.h
    mbed-os/platform/mbed_stats.h
    mbed-os/platform/mbed_toolchain.h
    mbed-os/platform/mbed_wait_api.h
    mbed-os/platform/NonCopyable.h
    mbed-os/platform/platform.h
    mbed-os/platform/PlatformMutex.h
    mbed-os/platform/rtc_time.h
    mbed-os/platform/ScopedLock.h
    mbed-os/platform/semihost_api.h
    mbed-os/platform/SingletonPtr.h
    mbed-os/platform/sleep.h
    mbed-os/platform/Stream.h
    mbed-os/platform/toolchain.h
    mbed-os/platform/Transaction.h
    mbed-os/platform/wait_api.h
    mbed-os/rtos/ConditionVariable.h
    mbed-os/rtos/EventFlags.h
    mbed-os/rtos/Kernel.h
    mbed-os/rtos/Mail.h
    mbed-os/rtos/MemoryPool.h
    mbed-os/rtos/Mutex.h
    mbed-os/rtos/Queue.h
    mbed-os/rtos/rtos.h
    mbed-os/rtos/RtosTimer.h
    mbed-os/rtos/rtos_idle.h
    mbed-os/rtos/Semaphore.h
    mbed-os/rtos/Thread.h
    mbed-os/rtos/TARGET_CORTEX/mbed_rtos1_types.h
    mbed-os/rtos/TARGET_CORTEX/mbed_rtos_storage.h
    mbed-os/rtos/TARGET_CORTEX/mbed_rtx_conf.h
    mbed-os/rtos/TARGET_CORTEX/SysTimer.h
    mbed-os/rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.h
    mbed-os/rtos/TARGET_CORTEX/rtx4/cmsis_os.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/Include/cmsis_os2.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/Include/os_tick.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include/rtx_evr.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Include/rtx_os.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_c.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_ca.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_cm.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.h
    mbed-os/rtos/TARGET_CORTEX/rtx5/RTX/Source/rt_OsEventObserver.h
    mbed-os/targets/TARGET_STM/gpio_object.h
    mbed-os/targets/TARGET_STM/mbed_rtx.h
    mbed-os/targets/TARGET_STM/nvic_addr.h
    mbed-os/targets/TARGET_STM/PeripheralPins.h
    mbed-os/targets/TARGET_STM/PinNamesTypes.h
    mbed-os/targets/TARGET_STM/PortNames.h
    mbed-os/targets/TARGET_STM/rtc_api_hal.h
    mbed-os/targets/TARGET_STM/serial_api_hal.h
    mbed-os/targets/TARGET_STM/stm32_assert.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/can_device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/common_objects.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/gpio_irq_device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/i2c_device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/pin_device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/pwmout_device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/spi_device.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/objects.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/PeripheralNames.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/PinNames.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/cmsis.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/cmsis_nvic.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/hal_tick.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/stm32l476xx.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/stm32l4xx.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/system_stm32l4xx.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can_legacy.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_comp.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_conf.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cortex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_crc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_crc_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cryp.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_cryp_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dac.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dac_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dcmi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_def.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dfsdm.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dfsdm_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma2d.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dma_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_dsi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_firewall.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_flash_ramfunc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gfxmmu.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gpio.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_gpio_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hcd.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_i2c.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_i2c_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_irda.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_irda_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_iwdg.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_lcd.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_lptim.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ltdc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ltdc_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_nand.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_nor.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_opamp.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_opamp_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_ospi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pwr.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pwr_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_qspi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rcc_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rng.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sai.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sai_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sd.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sd_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smartcard.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smartcard_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_smbus.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_spi_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_sram.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_swpmi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tsc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_uart_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_usart.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_usart_ex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_wwdg.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_adc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_bus.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_comp.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_cortex.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_crc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_crs.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dac.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dma.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dma2d.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_dmamux.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_exti.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_fmc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_gpio.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_i2c.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_iwdg.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_lptim.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_lpuart.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_opamp.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_pwr.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rcc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rng.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_rtc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_sdmmc.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_spi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_swpmi.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_system.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_tim.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usart.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usb.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_utils.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_wwdg.h
    mbed-os/targets/TARGET_STM/TARGET_STM32L4/device/stm32_hal_legacy.h
)
